name: Actions Runner Controller Demo
on:
  workflow_dispatch:

jobs:
  Test_ARC_frey-configs:
    runs-on: frey-configs
    steps:
    - run: echo "This job uses a self hosted runner scale set for frey-configs!"